### ISSUE TITLE
The size() function within $(...) worked incorrectly

### ISSUE THREAD

**Issue by davidhcefx** [mh21/indicator-multiload#2]
Within the embedded-code area $(...), instead of taking the number and divide it by `1024*1024`, the size() function divide the number by `1000*1000`.

**Comment by mh21** [comment]
You can use size2() for IEC units.

**Comment by davidhcefx** [comment]
> You can use size2() for IEC units.

I plugged in $(size2(mem.user)), but it showed nothing. Only size() function works.

**Comment by mh21** [comment]
This might be related to the version, it works for me with version 0.5.

**Comment by davidhcefx** [comment]
> This might be related to the version, it works for me with version 0.5.

Oops, I'm in version 0.4. The image on launchpad still remains at ver 0.4. It seems like you've not been developing it for a long time, maybe I should report to them instead of to you lol.
