### ISSUE TITLE
Is there some kind of log file?

### ISSUE THREAD

**Issue by davidhcefx** [mh21/indicator-multiload#3]
Is there some kind of log file that I can look into?
Because sometimes I suffer from a bug that the graph keep looping A and B without updating. I can disable the graph and re-enable it, but it still kept looping the same figure. I am still figuring out when would it happen, so some debug messages to inspect on might help.

**Comment by mh21** [comment]
Hi David,

not really. You can take a look at the pictures in /run/user/<id>/multiload-icons-<tmp>/icons/indicator-multiload-graphs-*.png to see whether the pictures update.

Cheers 

Michael
